### Variables
@baseUrl = http://localhost:3000

### 1. Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "goldCardNumber": 55501,
    "name": "Elsa Milhet",
    "email": "milhet@juniata.edu",
    "password": "securePass123",
    "dateOfBirth": "2002-05-15",
    "phoneNumber": 123456789,
    "prefersMusic": "Rock",
    "prefersConversation": "Yes",
    "prefersPets": "Dogs only",
    "prefersSmoke": "No",
    "driverLicense": "PA-987654321"
}

### 2. Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "milhet@juniata.edu",
    "password": "securePass123"
}

### 3. Get User Profile (Replace :id with a real goldCardNumber)
GET {{baseUrl}}/users/55501

### 4. Create a Ride 
POST {{baseUrl}}/rides
Content-Type: application/json

{
    "departureTime": "2:00:00",
    "date_": "2026-06-15",
    "destination": "Test",
    "availableSeats": 4,
    "price": 30,
    "goldCardNumber": 102
}

### 5. Get All Available Rides (Ta route actuelle)
GET {{baseUrl}}/rides

### 6. Filter Rides by Destination
GET {{baseUrl}}/rides?destination=Paris

### 7. Filter Rides by Date
GET {{baseUrl}}/rides?date=2026-04-01

### 8. Filter Rides by Destination AND Date
GET {{baseUrl}}/rides?destination=Paris&date=2024-06-15

### 9. Get Specific Ride Details (Success)
GET {{baseUrl}}/rides/RIDE-001
Accept: application/json

### 10. UPDATE a Ride (PUT)
PUT {{baseUrl}}/rides/RIDE-001
Content-Type: application/json

{
    "destination": "Lyon",
    "date_": "2026-07-15",
    "departureTime": "10:30:00",
    "price": 35,
    "availableSeats": 2,
    "goldCardNumber": 101
}

### 11. DELETE a Ride
DELETE {{baseUrl}}/rides/RIDE-004

### 12. Get all rides offered by a specific driver
GET {{baseUrl}}/users/102/rides
Accept: application/json

### 13. Get all comments and stars for a specific driver
GET {{baseUrl}}/users/55501/vehicle
Accept: application/json

### 14. Get all comments and stars for a specific driver
GET {{baseUrl}}/users/102/reviews
Accept: application/json

### 15. Confirm or modify the booking status
PATCH {{baseUrl}}/bookings/BOOK-503
Content-Type: application/json

{
    "status": "cancelled"
}

### 16. Create a new booking
POST {{baseUrl}}/bookings
Content-Type: application/json

{
    "rideID": "RIDE-004",
    "goldCardNumber": 55501
}

### 17. Get ALL bookings for a user
GET {{baseUrl}}/users/55501/bookings

### 18. Get only CONFIRMED bookings
GET {{baseUrl}}/users/55501/bookings?status=Confirmed

### 19. Get only CANCELLED bookings
GET {{baseUrl}}/users/55501/bookings?status=Cancelled

### 20. Get only PENDING bookings
GET {{baseUrl}}/users/55501/bookings?status=Pending

### 21. Delete a specific booking
DELETE {{baseUrl}}/bookings/BOOK-505

### 22. Update User Profile 
PUT {{baseUrl}}/users/102
Content-Type: application/json

{
    "name": "Kai Sterling Updated",
    "dateOfBirth": "2002-03-18",
    "phoneNumber": "814-555-0000",
    "prefersMusic": "yes",
    "prefersConversation": "yes",
    "prefersPets": "no",
    "prefersSmoke": "no",
    "driverLicense": "PA-88888888"
}

### 23. Add a new vehicle to a specific user
POST {{baseUrl}}/vehicles
Content-Type: application/json

{
    "plateNumber": "EAGLE-26",
    "model": "Ford Mustang",
    "color": "Blue",
    "goldCardNumber": 55502
}

### 24. Update existing vehicle details
PUT {{baseUrl}}/vehicles/55501
Content-Type: application/json

{
    "plateNumber": "EAGLE-2026",
    "model": "Tesla Model 3",
    "color": "Midnight Silver"
}